### PR TITLE
Update to node-addon-api v3.0.0

### PR DESCRIPTION
**Pull request by joelpurra**

### CODE REVIEW

**Comment by joelpurra** [comment]
Update is, from my point of view, unrelated to the previously reported `node-addon-api` vulnerability. Fixes #38 though.

**Comment by dennisameling** [comment]
@addaleax Any chance that this could be merged? The old `node-addon-api` version is causing build issues on Windows ARM64 in combination with Node 15.14.0. We currently [add the following](https://github.com/dennisameling/Signal-Desktop/blob/c3628c2abeaefd5a5c0641f12f821904955cc214/package.json#L293-L295) to the `package.json` and then it works perfectly:

```JSON
  "resolutions": {
    "zkgroup/ref-napi/node-addon-api": "3.2.1",
    "zkgroup/ffi-napi/ref-napi/node-addon-api": "3.2.1",
    "zkgroup/ref-array-napi/ref-napi/node-addon-api": "3.2.1"
  },
```

Please let me know if I can be of any help in terms of testing etc. 👍🏼

**Comment by addaleax** [comment]
→ `📦  ref-napi@3.0.3`

**Comment by dennisameling** [comment]
Thank you! Much appreciated 🚀

**Pull request merged**
