### PR TITLE
Update and rename jquery-1.7.2.min.js to jquery-3.5.1.min.js

### PR DESCRIPTION
**Pull request by AlAyoub**
Version bump to 3.5.1 for security reasons. 

Upgrade To:
jquery-3.5.0 or jquery-3.5.1
Downgrade To:
jquery-1.1.2, jquery-1.2.1a, jquery-1.2.2 or jquery-1.1.14

(This recommendation is as of 05/31/2020)

### CODE REVIEW

**Comment by AlAyoub** [comment]
Hi @addaleax, 

Thank you for merging last time this happened. For security reasons, jquery needs to be upgraded to jquery-3.5.0 or jquery-3.5.1 this time. I used the most current version. Please review and merge when you get a moment, thank you!

**Comment by AlAyoub** [comment]
need

**Comment by addaleax** [comment]
@AlAyoub I think you’d need to update the link in the docs that references the filename as well?

**Comment by AlAyoub** [comment]
oops, sorry I missed that. I just made the change now in index.jade to reflect 3.5.1

Thank you.

**Comment by AlAyoub** [comment]
@addaleax I have two open PR's, did you prefer that I closed them and make all changes in one PR? Or is that ok? Thank you.

**Comment by AlAyoub** [comment]
Hi @addaleax, all changes are on this PR. Thank you.

**Comment by addaleax** [comment]
@AlAyoub Thank you! Sorry I’m slow to respond on personal projects, but yes, it’s helpful to have everything in a single PR.

Do you need this to go out in a release? This only affects the documentation, but I assume you opened this PR because of some automated warning message?

**Comment by AlAyoub** [comment]
@addaleax Excellent, thank you so much. Yes, this particular bug was flagged in two of my applications and I'm hoping that it gets closed before July. Can you version bump?

**Comment by addaleax** [comment]
@AlAyoub Sure, done! :slightly_smiling_face: 

```
+ ref-napi@2.0.3
```

**Pull request merged**
